
package quizer.pro;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author amina
 */
public class newClass extends javax.swing.JFrame {
    Random rand = new Random();
    String code = "";
    String delim = ",";
    User current;
    String email;
    /**
     * Creates new form newClass
     */
    public newClass() {
        initComponents();
    }
    
    public newClass(User u) {
        current = (User)u;
        email = current.getEmail();
        initComponents();
        
    }
    
    public boolean checkName(String name){
        File f;
        boolean exists;
        f = new File(name+".csv");
        exists = !f.canExecute();   
       
        return exists;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        classNameText = new javax.swing.JTextField();
        fileText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ADD NEW CLASS");

        jLabel2.setText("Upload a TeachAssist .CSV file in the given text box");

        classNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameTextActionPerformed(evt);
            }
        });

        fileText.setText("example");
        fileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Class Name");

        jLabel4.setText(".CSV File");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("just name, don't need .csv at end");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(classNameText)
                                    .addComponent(fileText, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(addButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        
        String courseName = classNameText.getText();
        String fileName = fileText.getText();
        if(!checkName(courseName)){
            JOptionPane.showMessageDialog(null,
                "This name is already taken",
                "Error",
                JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        if(courseName.equals("") || fileName.equals("")){
            JOptionPane.showMessageDialog(null,
                "Please make sure all fields are filled",
                "Error",
                JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        //check if the file exists, if it does, create a new file with it, add it to a list of taken codes
       File f = new File(fileName+".csv");
       Scanner fromOld;
        try{
            fromOld = new Scanner(f);
        } catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null,
                "Please make sure you have chosen the correct name and path.",
                "No such file exists.",
                JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        
        File newFile = new File(courseName+".csv");
        PrintWriter pw;
        
        try {
            pw = new PrintWriter(new FileWriter(newFile));
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                "Please try again",
                "Unexpected Error.",
                JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        pw.println(courseName);
        //adds the course name and code to the teacher's all classes file - used to show what classes they are part of
        
        
        
        //print to file: Student Number,First Name,Last Name,Email,
        while(fromOld.hasNext()){
            String[] line = fromOld.nextLine().split(delim);
            System.out.println(line[0]);
            pw.println(line[0]+delim+line[1]+delim+line[2]+delim+line[3]);
        }
        
        PrintWriter toList;
        try {
            toList = new PrintWriter(new FileWriter(email+".txt",true));
            toList.print(classNameText.getText()+delim);
            toList.close();
        } catch (IOException ex) {
            System.out.println("Cant print to it");
        }
        
        fromOld.close();
        pw.close();
        
        

        //new runnable event
        java.awt.EventQueue.invokeLater(new Runnable() {
                    //void method run 
                    @Override
                    public void run() {
                        //make the class added page visible
                        new classAdded(current).setVisible(true);
                    //end method
                    }
                //end method
                }
        //close parameter
        );
          //make this frame disappear
          this.setVisible(false);    
          
          //else
          //just put an error thing
    }//GEN-LAST:event_addButtonActionPerformed

    private void classNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField classNameText;
    private javax.swing.JTextField fileText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
